package in.mahind.bootcamp.pattern_matching;

public class Application {
    public static void main(String[] args) {

        Object name = "Ford";

        if (name instanceof String) {       // 1. is object a String
            String s = (String) name;       // 2. declaration of new variable s
            System.out.println(s);          // 3. casting of object to String into variable s
        }

        if (name instanceof String s) {
            System.out.println(s);
        }

    }

    private static String formatter(Object o) {
        String formatted = "unknown";
        if (o instanceof String s) {
            formatted = String.format("String %s", s);
        } else if (o instanceof Integer i) {
            formatted = String.format("Integer %s", i);
        } else if (o instanceof Double d) {
            formatted = String.format("Double %s", d);
        } else if (o instanceof Float f) {
            formatted = String.format("Float %s", f);
        } else if (o instanceof Long l) {
            formatted = String.format("Long %s", l);
        }
        return formatted;
    }


    private static void testSwitch(int a) {
        switch (a) {
            case 1: System.out.println("1"); break;
            case 2: System.out.println("2"); break;
            case 3: System.out.println("3"); break;
            case 4: System.out.println("4"); break;
            case 5: System.out.println("5"); break;
            default: System.out.println("default");
        }
    }

    private static String formaterPatternSwitch(Object o) {
        // JDK 21
        return switch (o) {
            case null -> "null";
            case Integer i -> String.format("Integer %s", i);
            case Double d -> String.format("Double %s", d);
            case Float f -> String.format("Float %s", f);
            case Long l -> String.format("Long %s", l);
            case String s -> String.format("String %s", s);
            default -> "unknown";
        };
        // what about null check?
    }

    private static void test(Object o) {
        switch (o) {
            case String s:
                if (s.length() == 1) {
                    System.out.println("Length is 1");
                } else {
                    System.out.println("Length is not 1");
                }
                break;
            default:
                System.out.println("unknown");
        }
    }

    private static void guardedPattern(Object o) {

        switch (o) {
            case String s when s.length() == 1 -> System.out.println("Length is 1");
            case String s                      -> System.out.println("Length is not 1");
            default -> System.out.println("unknown");
        }
    }

    /*

    Helpful NullPointerException JDK 14

    Improve the usability of the NPE generated by the JVM
    by describing precisely which variable was null

    a.i = b.j;

    Exception in thread "main" java.lang.NullPointerException
    at Prog.main(Prog.java:5)

    Was 'a' null or 'b' null ??

    Exception in thread "main" java.lang.NullPointerException
    Cannot read field "j" because "b" is null
    at Prog.main(Prog.java:5)

     */


}
